### PR TITLE
successor on biinv-int which cancels pred exactly

### PR DESCRIPTION
**Pull request by ecavallo**
@mortberg 

Turns out it is entirely possible, just requires some IH-strengthening. I did `suc`, but `pred` wouldn't be any harder.

### CODE REVIEW

**Comment by mortberg** [comment]
Woah! And you convinced me that it wasn't possible today...

**Comment by mortberg** [comment]
Can you use these integers in the proof that Omega(S1) = Int ? If I remember correctly I think it will simplify the loop case of https://github.com/RedPRL/redtt/blob/master/library/paths/s1.red#L106

**Comment by mortberg** [comment]
I think my idea was that you don't need to compose with pred-isuc as it's definitional

**Comment by ecavallo** [comment]
Well, you would have to rewrite everything that does case analysis on `int` first...

**Comment by mortberg** [comment]
Yeah, my prediction is that that will be quite a nightmare with these integers...

**Pull request merged**
